### ISSUE TITLE
Enhancement Request: shifting pov with the mouse

### ISSUE THREAD

**Issue by zayaraq** [markcellis/X-Camera#11]
In the settings there is a keyboard binding for "Moves the camera with the mouse in a left-right / up-down fashion" and "Moves the camera with the mouse in a left-right / forward-back fashion". It appears to be too sensitive at the moment. An independent sensitivity setting for this would be useful to avoid having to change the movement increment settings.
Also shifting the view with the mouse and doing it with the arrow keys seems to work differently. The arrow keys will always move up/down and left/right relative to your pov while the mouse function seems to have a fixed direction for up and down. That makes looking down to check the center pedestral difficult with the mouse. I think an option to change the reference axis could be useful as well.
The last thing I noticed is that when panning the view with your mouse and using the arrow keys to shift it around at the same time the reference axis does not change until you let go of the right mouse button for xcamera views, but it does change dynamically for standard xplane camera views, making it feel a little less natural. I do think that's pretty minor, tho, because it probably does not happen too often. Could be useful for other people, tho. If you need more details about this like some in game video I can provide this as well of course.

Thanks again :)

**Comment by markcellis** [comment]
I added a mouse move factor to the settings page which will be available in 2.4.4 Beta 3. That should allow you adjust the amount of movement per pixel of mouse movement.

On the mouse move POV it seems to be working right for me. Remember, there are two mouse move modes, left-right/up-down and left-right/forward-backwards. If you pitch the camera down to look at the pedestal then it is a forward-back operation to move the camera up and down because it is pitched at -90 degrees. That is also the way the arrow and . / , keys work. As soon as you pitch the camera down it is a dot / comma key that moves the camera up and down.

You are right about the camera POV heading and pitch not getting updated until you release the right mouse button. I'm pretty worried about trying to change that as I might screw up a bunch of other stuff.

**Comment by zayaraq** [comment]
Thanks I'm looking forward to that! I do have a question about the mouse move pov still. I have mouse binds for both the "up-down" and the "forward-back" function. When I look out the front window it works as expected. However looking down to my center pedestal for example, both mouse functions will actually do the same (but with the forward-back part reversed) and they do not work exactly like the arrow keys. Since it seems to work for you I really hope there just are some settings that I need to tweak. Any idea what could be the problem? Thanks again :)

**Comment by markcellis** [comment]
Maybe we can connect on Discord so we can do a screen share and see what is going on.

https://discord.gg/KBDYEMUAsz
